### ISSUE TITLE
所选的插件不在编译范围内?怎么解决?谢谢!

### ISSUE THREAD

**Issue by ghaner** [281677160/build-actions#21]
![3f7JSdge9l](https://user-images.githubusercontent.com/51288907/137064928-b1f80c49-cb92-472b-afe7-11f602002ec1.png)
![W3S4ucGb8x](https://user-images.githubusercontent.com/51288907/137064940-9b400e0e-980b-4d31-a1f5-9fed78accc51.png)

**Comment by 281677160** [comment]
这个好解决啊，编译的时候连接SSH进去选择好插件，弄出配置文件来，然后覆盖到对应源码里面再进行编译不就行了？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/build-actions"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月13日(星期三) 中午12:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[281677160/build-actions] 所选的插件不在编译范围内?怎么解决?谢谢! (#21)





 

 
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 281677160** [comment]
请确认正确配置，谢谢，我到现在都还是老老实实的自己进SSH修改配置的，我没技术自己写
![QQ截图20211013150112](https://user-images.githubusercontent.com/66651997/137083304-db3af791-9924-428e-b99e-bf4c64deef5b.png)
![QQ截图20211013122915](https://user-images.githubusercontent.com/66651997/137083319-26fcf78f-07c6-4581-9ac7-dfbb389d576e.png)
