### ISSUE TITLE
最近两次编译，TTYD命令行均不能自动登陆，请教老大解决办法。。。

### ISSUE THREAD

**Issue by drw2005** [281677160/build-actions#22]
最近用LEDE和Lienol分别编译的两个版本都试了，ttyd打开不能自动登陆，需要手动登陆一下才行，这个是啥原因？老大给看看，谢谢！

![QQ截图20211015101844](https://user-images.githubusercontent.com/33473981/137425340-0d2ed1f2-afc5-4ff1-a184-a8a707d41979.png)

**Comment by 281677160** [comment]
为了安全吧，有些人是需要外网远程连接的，如果不需要密码就很危险，这个好像编译的时候加个命令可以搞，不过我没研究过




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/build-actions"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月15日(星期五) 中午11:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[281677160/build-actions] 最近两次编译，TTYD命令行均不能自动登陆，请教老大解决办法。。。 (#22)





 
最近用LEDE和Lienol分别编译的两个版本都试了，ttyd打开不能自动登陆，这个是啥原因？老大给看看，谢谢！
 

 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 281677160** [comment]
全都一样的啊，要输入帐号密码登录




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/build-actions"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月15日(星期五) 下午2:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [281677160/build-actions] 最近两次编译，TTYD命令行均不能自动登陆，请教老大解决办法。。。 (#22)





  
为了安全吧，有些人是需要外网远程连接的，如果不需要密码就很危险，这个好像编译的时候加个命令可以搞，不过我没研究过
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/build-actions" @.&gt;; 发送时间:&nbsp;2021年10月15日(星期五) 中午11:00 @.&gt;; @.***&gt;; 主题:&nbsp;[281677160/build-actions] 最近两次编译，TTYD命令行均不能自动登陆，请教老大解决办法。。。 (#22) 最近用LEDE和Lienol分别编译的两个版本都试了，ttyd打开不能自动登陆，这个是啥原因？老大给看看，谢谢！ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
之前编译的都能正常登陆，难道是最近取消自动登陆了？老大你编译的也是这样吗？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by drw2005** [comment]
> 不可能啊，你的什么源码的？你去看看etc/config文件夹里面有没有ttyd这个文件，然后把内容复制出来我看看
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "281677160/build-actions" ***@***.***&gt;; 发送时间:&nbsp;2021年10月15日(星期五) 下午4:03 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [281677160/build-actions] 最近两次编译，TTYD命令行均不能自动登陆，请教老大解决办法。。。 (#22) 你要自动登录就用命令吧，会对openwrt重启的，你要编译之前搞好的话，就用files文件替换法来替换 路径是 /etc/config/ttyd 下面命令是对openwrt执行的，执行完毕会重启openwrt sed -i 's//bin/login//bin/login -f root/' /etc/config/ttyd &amp;&amp; reboot 执行完没有重启，提示这个： sed: bad option in substitution expression 好像没起作用。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
内容如下：
config ttyd
	option interface '@lan'
	option command '/bin/login'
