### ISSUE TITLE
请教老大一个小米mini固件编译的问题

### ISSUE THREAD

**Issue by drw2005** [281677160/build-actions#26]
用的Lede_source源码，编译出来大概15m，刷新完固件，配置好上网环境，一切正常。但是只要一重启，所有配置就丢失了，这时查看软件包空闲空间，居然为0了，这到底是啥原因？

插件就添加了ttyd、ddnsto、VSSR和turboacc这四个。我看有些人发布的MINI固件添加十几个插件的都有，还有很多主题，也没这问题啊！

请教老大，这个是啥原因？有没有在添加上面几个插件的情况下减少固件体积的办法？

感谢！

**Comment by 281677160** [comment]
不了解，没这路由，也没听人说过这样情况




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/build-actions"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月2日(星期二) 下午4:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[281677160/build-actions] 请教老大一个小米mini固件编译的问题 (Issue #26)





 
用的Lede_source源码，编译出来大概15m，刷新完固件，配置好上网环境，一切正常。但是只要一重启，所有配置就丢失了，这时查看软件包空闲空间，居然为0了，这到底是啥原因？
 
插件就添加了ttyd、ddnsto、VSSR和turboacc这四个。我看有些人发布的MINI固件添加十几个插件的都有，还有很多主题，也没这问题啊！
 
请教老大，这个是啥原因？有没有在添加上面几个插件的情况下减少固件体积的办法？
 
感谢！
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 281677160** [comment]
百度了一下，恩山有类似的帖子，你自己看看
https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=5615078&extra=page%3D1%26filter%3Dtypeid%26typeid%3D44

**Comment by drw2005** [comment]
> 百度了一下，恩山有类似的帖子，你自己看看 https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=5615078&extra=page%3D1%26filter%3Dtypeid%26typeid%3D44

恩山相关帖子翻遍了，也没找到解决办法。

我之前7月份编译的都没这个问题，当时插件选的比现在的多。

**Comment by 281677160** [comment]
> > 百度了一下，恩山有类似的帖子，你自己看看 https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=5615078&extra=page%3D1%26filter%3Dtypeid%26typeid%3D44
> 
> 恩山相关帖子翻遍了，也没找到解决办法。
> 
> 我之前7月份编译的都没这个问题，当时插件选的比现在的多。

那你用4.14的源码编译测试一下呗

**Comment by drw2005** [comment]
> > > 百度了一下，恩山有类似的帖子，你自己看看 https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=5615078&extra=page%3D1%26filter%3Dtypeid%26typeid%3D44
> > 
> > 
> > 恩山相关帖子翻遍了，也没找到解决办法。
> > 我之前7月份编译的都没这个问题，当时插件选的比现在的多。
> 
> 那你用4.14的源码编译测试一下呗

我是本地编译，请教怎么退回到4.14版本？
