### ISSUE TITLE
编译完成后找不到固件

### ISSUE THREAD

**Issue by xiaoqi2020** [281677160/build-actions#27]
总耗时12分57秒就编译完成了，但是只有一个config、可以下载，找不到固件在哪里下载呢？

**Comment by 281677160** [comment]
我没有脚本能有这个编译速度，不好意思，不知道原因

**Comment by 281677160** [comment]
看了你才仓库，你根本就没弄密匙，触发不了自动编译

**Comment by xiaoqi2020** [comment]
> 看了你才仓库，你根本就没弄密匙，触发不了自动编译

啥钥匙？咋弄？

> 看了你才仓库，你根本就没弄密匙，触发不了自动编译

啥钥匙？咋弄的？没看到你说呢

**Comment by 281677160** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/build-actions"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月3日(星期三) 下午4:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [281677160/build-actions] 编译完成后找不到固件 (Issue #27)





  
看了你才仓库，你根本就没弄密匙，触发不了自动编译
  
啥钥匙？咋弄？
  
看了你才仓库，你根本就没弄密匙，触发不了自动编译
  
啥钥匙？咋弄的？没看到你说呢
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by starxu1971** [comment]
你好好看下说明都有怎么弄，弄好就能编译了。

**Comment by 281677160** [comment]
啊，哦，搞啥子飞机，我前面发的图片没显示
![QQ截图20211103162427](https://user-images.githubusercontent.com/66651997/140040388-6f560d8b-0b86-42ba-9f67-a2e841d29783.png)
啊

**Comment by xiaoqi2020** [comment]
固件编译好了，但是dockerman有问题

无法连接到docker守护进程（docker daemon），请检查!!

![image](https://user-images.githubusercontent.com/50669177/140321656-3a57eb6f-5a8f-4c21-a8e6-5f1db623d937.png)

**Comment by 281677160** [comment]
不了解，我昨天晚上编译的X86都还没问题的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/build-actions"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月4日(星期四) 晚上9:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [281677160/build-actions] 编译完成后找不到固件 (Issue #27)





 
固件编译好了，但是dockerman有问题
 
无法连接到docker守护进程（docker daemon），请检查!!
 

 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
