### ISSUE TITLE
OP_DIY文件跟openwrt文件是同一个目录里面，好像没找到啊，请教一下！

### ISSUE THREAD

**Issue by drw2005** [281677160/build-actions#34]
请教老大，本地Ubuntu一键编译脚本说明里：
问：“请在/OP_DIY/xxx_source里面设置好自定义文件”是什么意思？
答：OP_DIY文件跟openwrt文件是同一个目录里面。

WinSCP进去OpenWrt下好像没找到OP_DIY这个目录呢？

**Comment by 281677160** [comment]
为什么去openwrt文件夹下找？跟它同一个目录，不是在openwrt下好不好




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/build-actions"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月11日(星期六) 下午4:11
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[281677160/build-actions] OP_DIY文件跟openwrt文件是同一个目录里面，好像没找到啊，请教一下！ (Issue #34)





 
请教老大，本地Ubuntu一键编译脚本说明里：
 问：“请在/OP_DIY/xxx_source里面设置好自定义文件”是什么意思？
 答：OP_DIY文件跟openwrt文件是同一个目录里面。
 
OpenWrt下好像没找到OP_DIY这个目录呢？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by drw2005** [comment]
也没有：

![无标题](https://user-images.githubusercontent.com/33473981/145698717-c2376a52-c1ad-4944-a7fb-15931efea96b.png)

**Comment by 281677160** [comment]
![QQ截图20211212120127](https://user-images.githubusercontent.com/66651997/145699768-11a95d60-38af-48ae-91fd-d8ca6562f092.png)
那我也是没办法了，子系统，服务器版本的我都测试了，没问题的，就是下载一个文件而已，你的下载不了我也不知道什么情况

**Comment by 281677160** [comment]
![QQ截图20211212120618](https://user-images.githubusercontent.com/66651997/145699851-c6c49b88-859a-4fab-9298-2d7d598f6c42.png)

**Comment by drw2005** [comment]
是我的原因，我用还是之前的一键编译命令，才看到新的bash <(curl -fsSL git.io/local.sh)
这下本地更方便了，越来越好用，谢谢老大！

**Comment by drw2005** [comment]
本地要是再支持定制banner就好了，老大能实现不？
